---
title: "pcurveMix Fit Report"
date: "`r format(Sys.time(), '%Y_%m_%d_%H_%M_%S')`"
output:
  word_document:
    reference_docx: pcurveMix_style.docx
params:
  p_filename: NA
  descriptor_tbl: NA
  estimates_tbl: NA
  pdf_plot: NA
  cdf_plot: NA
  n_boot_samples: NA
  boot_pct_converged: NA
  boot_tbl: NA
  profile_analysis: NA
  profile_tbl: NA
  profile_mu_plot: NA
  profile_sigma_plot: NA
  profile_pi_plot: NA
  profile_power_plot: NA
  profile_folded_normal_mu_plot: NA
  profile_folded_normal_sigma_plot: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 6, fig.height = 4)
# Fitting observed $p$ values with the mixture model of Ulrich & Miller (2026, submitted).
```

# Maximum-likelihood fitting summary

## Fitting parameters and summary results

```{r print_fitting_parameters, echo=FALSE, results='asis'}
print(knitr::kable(params$descriptor_tbl))
```

## Parameter estimates

```{r print_parameter_estimates, echo=FALSE, results='asis'}
print(knitr::kable(params$estimates_tbl))
```

## Observed/predicted PDFs:

```{r plot pdf, echo=FALSE}
plot(params$pdf_plot)
```

## Observed/predicted CDFs:

```{r plot cdf, echo=FALSE}
plot(params$cdf_plot)
```

```{asis, echo = params$n_boot_samples > 0}
## Parametric bootstrapping analysis
```

```{r echo=FALSE, results='asis', eval = params$n_boot_samples > 0}
cat(paste0("* n bootstrap samples = ",params$n_boot_samples,"\n"))
cat(paste0("* percent converged OK = ",params$boot_pct_converged,"\n"))
```

```{r print_boot_tbl, echo=FALSE, results='asis', eval = params$n_boot_samples > 0}
print(knitr::kable(params$boot_tbl))
```


```{asis, echo = params$profile_analysis > 0}
## Profile analysis
```

```{r profile_plots, echo=FALSE, eval = params$profile_analysis > 0}
plot(params$profile_mu_plot)
plot(params$profile_sigma_plot)
plot(params$profile_pi_plot)
plot(params$profile_power_plot)
plot(params$profile_folded_normal_mu_plot)
plot(params$profile_folded_normal_sigma_plot)
```

